
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

template:                                                                                                                                                                                                                          
  - trigger:
    sensor:
      name: 'ESB electricity usage'
      availability: 'false'
      state: 'none'
      unit_of_measurement: 'kWh'
      state_class: total_increasing #https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-sensorstateclasstotal_increasing
      device_class: energy
      unique_id: 'esb_electricity_usage'
